### ISSUE TITLE
WHAT THE FRESH FUCK IS THIS FOR

### ISSUE THREAD

**Issue by Derpius** [Mee12345/gwater_rewrite#10]
https://github.com/Mee12345/gwater_rewrite/blob/main/Simulation.h#L44

WHAT ARE YOU DOING

**Comment by Derpius** [comment]
GG 2 line variable shadowing https://github.com/Mee12345/gwater_rewrite/blob/main/Simulation.h#L44-L46

**Comment by Derpius** [comment]
Not fixed

**Comment by Andrew-Eathan** [comment]
@Derpius
